name: Hugo 🔧

on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      VIMEO_TOKEN:
    inputs:
      deploy:
        type: boolean
        default: false
      s3_bucket_name:
        type: 'string'

jobs:
  hugo-workflow:
    # Needed to make puppeteer work on GitHub Actions
    # See https://github.com/puppeteer/puppeteer/issues/12818
    # runs-on: ubuntu-latest
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout workflow ⬇️
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      with:
        repository: 'gauntface/workflows-static-site'
        path: 'workflows-static-site'

    - name: Checkout site ⬇️
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      with:
        submodules: true
        path: 'hugo-site'


    - name: Install Go  🛠️
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7
      with:
        go-version: '^1.18.3'

    - name: Install Hugo  🛠️
      uses: peaceiris/actions-hugo@2752ce1d29631191ea3f27c23495fa06139a5b78 # v3
      with:
        hugo-version: '0.152.2'


    - name: Install action Go Deps 🌎
      run: |
        go install github.com/gauntface/go-html-asset-manager/v5/cmds/htmlassets@latest
        go install github.com/gauntface/go-html-asset-manager/v5/cmds/genimgs@latest
        go install github.com/tdewolff/minify/v2/cmd/minify@latest

    - name: Install action NPM Deps 🌎
      run: |
        cd ./workflows-static-site/
        npm install

    - name: Install site NPM Deps 🌎
      run: |
        cd ./hugo-site/
        npm install


    - name: ESLint 🌟
      run: |
        cd ./workflows-static-site/
        npm run eslint    -- '../hugo-site/' --no-error-on-unmatched-pattern

    - name: Stylelint 🌟
      run: |
        cd ./workflows-static-site/
        npm run stylelint -- '../hugo-site/**/*.css'

    - name: Prettier 🌟
      run: |
        cd ./workflows-static-site/
        npm run prettier -- '../hugo-site/**/*.css' --check


    - name: Configure AWS Credentials ☁️
      uses: aws-actions/configure-aws-credentials@e1e17a757e536f70e52b5a12b2e8d1d1c60e04ef # v1-node16
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-1


    - name: Generate images 🖼️
      if: ${{ inputs.deploy == true }}
      run: |
        cd ./hugo-site/
        genimgs

    - name: Build 🔧
      run: |
        cd ./hugo-site/
        hugo

    - name: PostCSS 🔧
      run: |
        cd ./hugo-site/
        node ../workflows-static-site/src/postcss.js

    - name: HTML Asset Manager 🔧
      run: |
        cd ./hugo-site/
        htmlassets --vimeo=$VIMEO_TOKEN

    - name: Minify HTML 🔧
      run: |
        cd ./hugo-site/public/
        minify -r --match="*.html" -o . .

    - name: Project Tests 🧪
      run: |
        cd ./hugo-site/
        npm run test --if-present

    - name: Action Tests 🧪
      env:
        WORKFLOWS_SITE_PATH: '../hugo-site/public/'
      run: |
        cd ./workflows-static-site/
        node ./tests/browser-tests.js

    - name: Deploy to AWS 🌤️
      if: ${{ inputs.deploy == true }}
      run: npx --package @gauntface/cli gauntface aws s3 deploy-static-site --directory="./hugo-site/public/" --bucket_name="${{ inputs.s3_bucket_name }}" --delete_exclude="generated/*"
      shell: bash
